loki:
  test:
    enabled: false
  
  minio:
    enabled: true
  backend:
    persistence:
      enableStatefulSetAutoDeletePVC: false
  loki:
    auth_enabled: false

  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false

  enterprise:
    cluster_name: workshop_k8s-loki