loki:
  minio:
    enabled: true
  backend:
    persistence:
      enableStatefulSetAutoDeletePVC: false
  loki:
    auth_enabled: false

  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false