enabledComponents:
  traefik: true
  certs: true
  externaldns: true
  rbacmanager: false

certs:
  installCRDs: true

externaldns:
  provider:
    name: cloudflare
  sources:
    - traefik-proxy
  txtPrefix: drago
  txtSuffix: workshop
  extraArgs:
    - --cloudflare-proxied
    - --cloudflare-dns-records-per-page=5000
  env:
    - name: CF_API_KEY
      valueFrom:
        secretKeyRef:
          name: cloudflare-global-token
          key: api-token
    - name: CF_API_EMAIL
      value: "ioudkerk@gmail.com"

traefik:
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
  service:
    annotations:      
      load-balancer.hetzner.cloud/http-redirect-https: "false"
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/name: traefik
      load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
      load-balancer.hetzner.cloud/use-private-ip: "true"