enabledComponents:
  traefik: false
  certs: true
  externaldns: true
  rbacmanager: false

certs:
  installCRDs: true

externaldns:
  providerName: cloudflare
  extraArgs:
    - --cloudflare-proxied
    - --cloudflare-dns-records-per-page=5000
  env:
    - name: CF_API_KEY
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token-secret
          key: api-token
    - name: CF_API_EMAIL
      value: "ioudkerk@gmail.com"