{{- if .Values.persistent.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "magneto-hr.fullname" . }}-pv
  labels:
    {{- include "magneto-hr.labels" . | nindent 4 }}  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: hcloud-volumes
{{- end }}