apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: platform
spec:
  encryptedData:
    api-token: AgBoxrwTjLAmxsL8FSwudhjmFbflgLV5/npqjk3FI3p8GGt+ca9T/j1K6l4AqtkyoUQiHhmTieIyO8EhXRYDEa/2YJPz4gQhPtIi4F9R/APCO4/P9xx5nIdbfb4tLDTCJ5FQxCiU6vH1yOOrTyHMtUi0tkQD++B7nnVVn8jwI00KZ38NE9CaWzDl73bomu8bxmDyiTDBnhcS0/ZJZMOIIfoTf45aOPR36/fq+Fv09DSK33hvOj3kgjsJDpONwulwloqZ4cPpUGvq7IwtFQVh8V0DVUvVobW8vpRNDM4XVAalui1BDl8Ny0q5yvBFxcB/HaOsbIPixILyaOGJrUTl5gbRhSgqDWGSL09iHbVwd0+E5m5Ur8NFOFKG6buI+RAlkVCly6dAnALj4Cjhu9GI9IQomJxCYvvRiS/cihaPwIHXTSLloDZlJL6J7wMf38ECnzIlTIXLar00evNy+ZrqcmtnGFaS5HEXajmIF3a+hL+Y4NWNTj3ctfE4+88cCkKZvjTH4SxMRKo0o8IhDX62oWu3QBtEzg4ZLA0ZZtw7VFequVeH4kb381KPpnOMS1RV0kLpCLeHH6cB0L1m+pHrr5gCypbZrrKs3QFBs2d59QXIG+hxlTMXmxwIrk0RfeAdiJggseFGftZ5eRjM9U0ZxljGRA7kwYN9DnjtnhtzBOoEzb7xRZUVjpv0jMPihxRjOfp7elnGAHuZ3t7OsJa/k2gFaHavxFCbsgMH4zCbTezHEUzAknOMtiuP  