apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: platform
spec:
  encryptedData:
    api-token: AgAWz7iglqpWQpP7XEt9Zc0IADy2PZXnt4VcJ3djshCDEWbFZHZn8BCQyyZOt7qJ/kW4/6YSUjc2g2gR7L316JYI+YQnQzAlKhZ1Li3SuDHI8UK67BEIzK19ojp4tSoXS9VKfIPZaSwTxKjHGLpCkKXRinKjK53xLhp1CBXTLYlcEuTkaobLMX8tDgxvoDqHU2fIsJp39TMMgKekt0N1yzRnVgVdT/9wRyKuehJfZ9yoULpPGLss2CQtgj5FNNdXIvldGD7trMjiONb/wLBBF61g2BZGaJnkB2nNHhF0V4RAsThClaV4UFYVp8pbmVlkq9GOQakcIYMom1tFFboqgQurOLPtbcs0KgywTulUd8PfokW/DU2/NBmK533jHZcspCUv4MEJY5bfc/PVtYBKnRzn7T12OOEmsK0qaAx7VOYnsZUh+vxbFc0D48w1g4fU38w7vjO7pdPQCnGKEn0FXY65wFCVOgiQAjMG9efTD0BR0IT7p1lxw7YY9ghzzctRsufYu6W6U6NO1r9/OZztw+aSMYC3kudpSo1ZfQCvpSPiV4xizbmSRsJnupBkKN3Za2wxu7bnxKNslVvuycZx2m+uTWI0etdSVHifxfv03p1Azbq8gf7s0ztazhO914xJTFBAwDHKjKhKUUGL00is2DRWhNxCu3YJ2ihHKoVL5ovcfci+Pnc8OyNWhBhihFMoZpPmggppLZn82IuSfge+B6UY7bkK9SCtB3LQSLhlc3MlnLMu3QaZdttia2xHWHYqVEd91oBgcS5lhw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: platform
    type: Opaque

