apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: platform
spec:
  encryptedData:
    api-token: AgBSZuIuV9LVIQAl7c70MtvpH9mWTxey86ikLTKBCBfSddyYfUC0/vk28lSJVLgyBNs9dPahkhBmkMm6FcuT6J5/W88uUbQLDI1tAPC9VkWkfvf8XJZJDIf+kkcVzE+ZCaO3tyaZjmxl2rEcF7LlG8iFsV60XoD2GcCa2oQBYVXuQEjrEl5P+bmHEk0/9R+nKfWm3xfiGoBED9yAo4SwQQjCKVYjliSLhHdCxmdeBHQeeaVPjeP2ji+2rcYKWr8L/SMJfIPwhyWn8cQ0xS4KquGGRNDnYuD8GaSEYbyb8fCQMG1WBWfgGEvBYO+ErlTaTuXVr+LzJDnoaov62S7hnaGeNMcjmHDcLOO2zqEJNdx7WMnnYut42tqB5qD6j9M2GF94AQit3J4ZwB5IwgK6gLMJk3TJPEWtRjL6N06X2zwKP5RMdK21BUgqpapzeW0Tmz6xHv9qzy0QCV2jdwozxpUOEEuqt4A2eb9LL0B5HybrXMU4Rk1H0xeLU6kE23JiJ5m1nZUTGDWlRrYKHdA/J9tvDBAXpCMvb9/TGuKzg569Hya2OHmtfDetU5/FevavCw8/HhUO4ZjLV8NNUAD6cRa7+oA+kVEGkJMLfTPJGTqXucXlZVdXaLjvEuNvSkEeHE8R7dBtmDCvwLMSb+gIUV9nQR4ZMVFNsrqxW0fNHkCWVfq/6HG70sLYHGCJPlkNzWZjK/PNE6ZqINZW/ic9YDFn7Zbg5l9wsKf/5VgYvfHLSDvNuB6qOotU