apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-global-token
  namespace: platform
spec:
  encryptedData:
    api-token: AgBGR82uqxXHO33KZGozVRCWD6Rv8JmaJVErOo/f8OFZR9bH0FhNziiZuP7e5EqC0Fc4xNNFnn7xO4sYADaCPmmze4b0lbQjFy7DWY3pTr2xMCFKHmbepbw+qMLWECtawCIwpKMg2Oon0W7X7Kcq6FecVYGVcpAmG0iR+LzlfD/28U1HLBR8d57bblyqrsmS+TjiP9RMKwrOQC5YZyLbScHazxrZHWm6FWq0Cts+IrjU9UTEYVVDl6VzeTvocVTlGDv6/SuQXk6s2MgSiDb02rIgYEN5BG/Y9Yrb3sLh0NkoAshQey98Raw+KM5hazVEGvbjXNGe9iHd+HLh92rnuGI3NYTlwp0ETmx3cH93wWAqtzdhjobyB6klCLk2ycUEGWzRci3ffD9oj3bbxM/QqD9++ZBbEdrq9LqZVetKc2CFkUQAEPBsAECRDm3u4YfzgVQ7F4xr8TD+FscKRkP7tNPQlLx59ZLzdmRm2biiC5bcb/zi51Qj54oGA57DbZ/yHdSUmD0146jsti/FEzxE8wV1VTuBcOIBaS9aXcUOoTD8u3r4xWHN3M+2C+qEg8Vanq9o46RjDSrZn8ZIrwLyf09s4r5HtgbWYQIVVLXCW+KkZZqoejKehJiphMbV2rtuZssKVFfbSIMGxe8zUW3RK0qMi9P3jfZxGIYX/lg8JqUmrLPikNic4on1FD/dh0nLAywJf0XqVowqwjqm7KQx28ovB3YmKBVUFK0lzW+va4qAOoZhoiHc