apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-global-token
  namespace: platform
spec:
  encryptedData:
    api-token: AgBqDnFtZNlKQ3mSH9DsEhlk7NYIwLXYmXREE3dtxzjTjCaOiG8vPUOcdU8N6QjjU2LyFQUegvqq4xo1wISWx29y7UnldBKAo/QISiSyM8johByHy352+BD7vlD7lf6qmbbU3GhRspgUq/ZHFLX70jpUT9BzvlTZojSGLQfBpb7pAo9S8neMRlqo1+mV6bm4wLTVN54MFdR5xKZ5C5RwEkv1kRvaTIbMq9appp3W3CArVX0LNVQ79ER7IU5hqvLM32+ieFX2rMB3kEGmUUxzhM/3ndi974XfJboKauDOPydDaGRLs4qUmznnQ3nMUQsfFV8qT93ZqfZ9ttAHASa3/aAnjLVerV8T6Bf9uabDj91PUXnNcCbfqP/nNoIbVuBD9uxon+Opl3gJ0iPO28c7KHA0vQ7HZV35/dUzrd/5x9iO4v/Ryeui6KvbvHvIB3qbDd4Aorbv9CaSbyGipIDFO8b/sXCp7QCIHAMl9UDOl8mkKvv0Ey+gkfl5rTDN4/nutz0p9hHfRrJepzByX/S5CL26nc8UxuNww1E/fMtC2NGmHfdeIO2lgs8lcsxvj+mANeFxhS+XRBr7i6kw/IAdJmKzrD7V59LjcDXg/5zYtpXcCUxQhebgwKmGZ6foHnGyTACG4dzebpN7JWzztXrJqgwJK82T3WLU4rEvsNS2D53uCzNev4o9oZwfm6bMbCSNWQ54Rsf0wPXgPuaIWbKqQm1iIu8/zQVxJd2si/8shdJkSffaU7G2