apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: platform
spec:
  encryptedData:
    api-token: AgB6T4a2diX8c+p+0HJ8zOVanMXV3i9gO/TQBOekPpwEQSdWp5VDgbrjRuseY3HxXw8Qmtl19TfvIRGHwhoxZtCHa7JlCl1jDIYf5KyPQTd7AD9Zr3WoleWVy7Rbu/4W8ToA5wcSkXRf3sPRSDuyxaSsyejDKHxN60nY/a84DzGi0AQkLiYDzAWNiYcKGOBT/zxzpfxIhpku7fOPKvhNye+FA7FonQ6UIRz/OKd4b59InzOiWYH5uB0xZWMdhkZJAJaiOSoLMiAxLJ/16G/NYxCr8jcuyF/NP6SUP+RHbTsYKk+25hlrI0N91SykrkMPwRm8JYKcVNPlYdem/NJFrEt5ZkflF7FGyl5rgdor9zNd104Zya6TQsn9lcNgCQofGgjYkDwBMH3Ly/5dN0Rpcdf2DaR7G1UKP3YVPqMghb51hImGVeg4yRBbuq8/gb64homMjvORdwuhE9ehamRpAKXOVer22/RTiz04/9PsDqmutUv6YD6vv9FCJlBAinnqtrtl7PS0lDQteHjRbQ++kN0dwT5HdUz+0kurdTYyYvLEddzDRbImQl81I0bIl44LvQ+nlpHfiYtJobhm0uo9ufPl+HIfz80tm6yYi6ItggHAviLNQKk5On1lUDpx6YGl7yfh1i8BaprxZ2qbb0K3KbB1iCT7V1UlgvBVSPkuF4cJfpSpSW9ATuSJAEbYAB+rDativy6gpPiokJ42pCiPYQhHGgKnzF/Q9M78kkJ1Nw+hPsfw5aD2B3oz