apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "blueprint.fullname" . }}-traefik
  labels:
    {{- include "blueprint.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: blueprint-platform
      app.kubernetes.io/name: traefik      
  podMetricsEndpoints:
    - port: metrics