replicaCount: 1

image:
  repository: ghcr.io/ioudkerk/ioudkerk/ml-genai
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 5000

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  dns: magneto-hr.aivandrago.me
  issuer:
    name: cloudflare-issuer
    kind: ClusterIssuer
  cloudflareProxied: "true"
  ttl: "300"
  target: "49.13.40.206"

env:
  DNA_DB_PATH: /app/data/stats.db
  FLASK_ENV: production
  FLASK_HOST: 0.0.0.0

persistent:
  enable: true
  size: "10Gi"
  mountPath: "/data"

volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: "magneto-hr-pv"

volumeMounts:
  - name: data-volume
    mountPath: "/data"